name: Docker Image CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Git Checkout
        uses: actions/checkout@v2
      - name: Docker Setup QEMU
        uses: docker/setup-qemu-action@v2.0.0
      - uses: docker/setup-buildx-action@v1
        id: buildx
        with:
          install: true
      - name: Build and push with Buildx
        run: docker build --platform linux/amd64,linux/arm64 . --tag jungsoft/alpine-nginx-forward-proxy --tag jungsoft/alpine-nginx-forward-proxy:1.25.4 --push
